
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.robertob.p1compi1.InputFileHandle;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAG_ATTRIBUTE_NAME = 11;
  public static final int TAG_NAME_PROJECT = 8;
  public static final int TAG_ATTRIBUTE_LOCATION = 12;
  public static final int TAG_NAME_FILE = 9;
  public static final int TAG_OPEN = 2;
  public static final int TAG_SELF_CLOSE = 7;
  public static final int EOF = 0;
  public static final int TAG_CLOSE_REVERSE = 4;
  public static final int error = 1;
  public static final int QUOTE = 6;
  public static final int ILLEGAL = 14;
  public static final int EQUALS = 5;
  public static final int TAG_CLOSE = 3;
  public static final int TAG_ATTRIBUTE_VALUE = 13;
  public static final int TAG_NAME_FOLDER = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TAG_OPEN",
  "TAG_CLOSE",
  "TAG_CLOSE_REVERSE",
  "EQUALS",
  "QUOTE",
  "TAG_SELF_CLOSE",
  "TAG_NAME_PROJECT",
  "TAG_NAME_FILE",
  "TAG_NAME_FOLDER",
  "TAG_ATTRIBUTE_NAME",
  "TAG_ATTRIBUTE_LOCATION",
  "TAG_ATTRIBUTE_VALUE",
  "ILLEGAL"
  };
}

